server:
  port: 8080

spring:
  application:
    name: consul-client
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /health
        healthCheckInterval: 20s
      host: localhost
      port: 8500